title = "Binder"  # From Git
gitRepoUrl = "https://github.com/Pr0pelled/Binder" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
# favicon = ""

# From git:
organizationName = "Pr0pelled"
projectName = "Binder"
url = "https://organizationName.github.io"
baseUrl = "/Binder/"
tagline = "A custom binder implementation using CollectionService"

[home]
enabled = true
includeReadme = false

[footer]
style = "dark"
copyright = "Copyright © 2022 Pr0pelled. Built with Moonwave and Docusaurus"