[package]
name = "pr0pelled/binder"
description = "Bind classes to Roblox Instances using CollectionService"
version = "0.1.0"
license = "MIT"
authors = ["Pr0pelled"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

include = [
	"src",
	"README.md",
	"wally.toml"
]

exclude = [
	"docs",
	"build",
	"Packages",
	"aftman.toml",
	"default.project.json",
	"moonwave.toml",
	"selene.toml",
	"wally.lock"
]

[dependencies]
Cleanser = "robloxiandemo/cleanser@^0.1.8"
Signal = "robloxiandemo/signal@^0.1.9"