[package]
name = "pr0pelled/binder"
description = "Bind classes to Roblox Instances using CollectionService"
version = "0.1.3"
license = "MIT"
authors = ["Pr0pelled"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"

[dependencies]
Cleanser = "robloxiandemo/cleanser@^0"
Signal = "robloxiandemo/signal@^0"